# Site settings
title:          mkorman.online
description:    "Nothing here yet"
baseurl:        ""
url:            "https://mkorman.online"

# Author
author:
  name:         Michał Korman
  url:          https://mkorman.online
  email:        michal.korman [AT] icloud [DOT] com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

exclude:
  - Gemfile
  - Gemfile.lock
  - THEME_LICENSE
  - tale.gemspec
