# Site settings
title:          mkorman.info
description:    "Nothing here yet"
baseurl:        ""
url:            "https://mkorman.info"

# Author
author:
  name:         Michał Korman
  url:          https://mkorman.info
  email:        michal.korman [AT] icloud [DOT] com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
